Repository ucsb-cs156-s23/proj-happycows-s23-6pm-3, pull requests merged in 2023-06, with the labels that each got.

#28 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff

#30 MS updated storybook component
  frontend/src/stories/components/Commons/ManageCows.stories.mdx
Labels: 5

#32 AD cow lot buy
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CowLot.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CowLotRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: enhancement, 10

#33 JE Implemented price change methods and attributes
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10

#35 JE Completed priceChange form, table, and tests
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
Labels: 10

#46 Ad cow lots sell functionality
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CowLotRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: enhancement

#48 Ad cow lots optimization to combine lots
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CowLot.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CowLotRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: enhancement, 10

#38 JE price change commons
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: Merge Candidate
